### ISSUE TITLE
Carrousel : compatibility with Koha 20.11

### ISSUE THREAD

**Issue by fridobox** [inLibro/inlibro-koha#36]
Hi,

With Koha 20.11, Carrousel display is broken.
I'm using last version 3.7.

![Screenshot_2021-04-29 Catalogue Ma bibliothèque](https://user-images.githubusercontent.com/30493086/116572429-a2c21300-a914-11eb-91bb-8cfc07ccfe39.png)

**Comment by fridobox** [comment]
Something with CSS position maybe

**Comment by fridobox** [comment]
Any news ?

**Comment by fridobox** [comment]
Ohhh

The rules for classe like "carousel-caption" come from Bootstrap CSS file.

Big changes from Bug 20168 https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=20168
means at OPAC there is no  Bootstrap CSS file anymore.

**Comment by fridobox** [comment]
You may find some help here :
https://getbootstrap.com/docs/4.3/components/carousel/

**Comment by philblou** [comment]
We'll be looking at it now.  It's quite probable that we end up with a branch for 20.05, if a solution to make it work for before-and-after 20.11 is not clean.

**Comment by philblou** [comment]
The fix is in version 3.9.  I'll close this bug
