### ISSUE TITLE
Carrousel : Fix worlding of setup page

### ISSUE THREAD

**Issue by fridobox** [inLibro/inlibro-koha#37]
Hi,

If no Carrousel is not configured, going to "run tool" displays an alert "You have no lists or none are set to be generated!".
https://github.com/inLibro/inlibro-koha/blob/14714c4672c7607483935888fe21c6cc1610eead/plugins/Koha/Plugin/Carrousel/step_1.tt#L29

You should change because Carrousel uses not only lists now.
Maybe just "You have no Carrousel to be generated!"

**Comment by alex6ripetti** [comment]
Hi, 
Is "<strong>You have no Carrousel to be generated!</strong> Create lists, reports or collections and set them so you can generate carousels." better ?

**Comment by fridobox** [comment]
What about 
"You have no Carrousel to be generated! Go to plugin configuration to create them"
