### ISSUE TITLE
Carrousel : compatibility with 21.11

### ISSUE THREAD

**Issue by fridobox** [inLibro/inlibro-koha#46]
https://github.com/inLibro/inlibro-koha/blob/6607649639ec681daf24b369ffbe9c5277259dc1/plugins/Koha/Plugin/Carrousel.pm#L424

In 21.11 Koha::News has been renamed :
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=24387

**Comment by fridobox** [comment]
Koha 21.11.00 is released.
Can you have a look please ?

**Comment by philblou** [comment]
We'll priorize it now

**Comment by philblou** [comment]
Alexis has fixed the issues, while preserving backward compatibility.
