### ISSUE TITLE
Carrousel : remove warn 'Querying provider'

### ISSUE THREAD

**Issue by fridobox** [inLibro/inlibro-koha#7]
When generating Carrousel, you get a lot of warns, for example :

``
[Koha::Plugin::Carrousel] Querying provider 'OpacCoce', /cover?id=8437604109&bn=243972&provider=&thumbnail=1
[Koha::Plugin::Carrousel] Querying provider 'OPACAmazonCoverImages', https://images-na.ssl-images-amazon.com/images/P/8437604109.01.MZZZZZZZ.jpg
``

Looks like this is for debug.

Can it be removed or in comment ?

**Comment by maryse-simard** [comment]
Il est vrai que ces logs n'ont d'autre utilité que pour le déboggage. Puisqu'il existe d'autres warn pour les messages d'erreurs, nous pouvons retirer celui-ci.
